### ISSUE TITLE
Where can I find training dataset 

### ISSUE THREAD

**Issue by sparkydogX** [lmb-freiburg/rgbd-pose3d#1]
Thank you for your great work.
I want to reproduce your result.But I can't find the dataset for training and testing . 
Is this dataset published? If published , can you tell me where can I find the dataset ?
Thanks in advance.

**Comment by zimmerm** [comment]
Thank you for your interest. The dataset is not released yet and will be provided on a by request basis.

**Comment by bearpaw** [comment]
Hi @zimmerm 
Thanks for the great code! I am also interested in your dataset. How can I get the access to the dataset? Thank you very much!

**Comment by zimmerm** [comment]
@bearpaw Unfortunately, I didn't find time for a clean up in the repository after the deadline rightaway and then lost it out of scope lately. Thanks for bringing the issue up again. I hope I can get to it sometime soon.

**Comment by ngalym** [comment]
Hi @zimmerm I am also interested in the dataset. Is it available to test the code. I could only run the forward_pass.py and see the points on png. Thank you.

**Comment by baniks** [comment]
Hi @zimmerm I had earlier wrote to you about the dataset. It would be really helpful if you can manage some time to upload the dataset (MKV or the captury dataset). Thank you in advance.
