### ISSUE TITLE
I want to know 'Naive Lifting' is whose works

### ISSUE THREAD

**Issue by huigoing** [lmb-freiburg/rgbd-pose3d#11]
hello ,I am interested in your work .i have a little problem . i read your paper and i see you compare your work with named 'Naive Lifting' .but you don not tell 'Naive Lifting' is  whose work. i want to study futher it .can you tell me 'Naive Lifting' is whose works. thank you

**Comment by zimmerm** [comment]
I didn't follow any specific paper for that baseline approach, but rather implemented it myself.

**Comment by huigoing** [comment]
Thank you for your so fast response to me. Can you be  will to share the code of 'Naive Lifting' ? haha.
