### ISSUE TITLE
Possible to run on CPU?

### ISSUE THREAD

**Issue by awesomebytes** [lmb-freiburg/rgbd-pose3d#12]
Hello,

I'm currently downloading the weights and the repo (it's going to take a while). I  wanted to try to run the network on a low powered robot (Atom 1.6Ghz 4x core, no dedicated gpu). I saw in the comments of `forward_pass.py` 1-2Hz results on beefy GPUs. Do you think it is worth testing on my use-case?

Thank you.

**Comment by zimmerm** [comment]
If you can afford a long runtime it might be worth trying. I haven't tried it running it on CPU yet, so I don't really know what runtime to expect.
