### ISSUE TITLE
Problem with 3d plot

### ISSUE THREAD

**Issue by Dzhange** [lmb-freiburg/rgbd-pose3d#2]
Thanks for the code!
But I simply can't draw a 3D plot with forward_pass.py I tried to call the 3d limb Coco function but it doesn't look like the teaser, and hand_plot_3d simply don't work. What is the right way for me to get a plot like the teaser?

**Comment by zimmerm** [comment]
There is no code that reproduces the teaser in this repo. forward_pass.py
will show detections on the "color.png " frame.

2018-07-12 20:16 GMT+02:00 zhang-ge <notifications@github.com>:

**Comment by Dzhange** [comment]
I got that... by the way, I tried some rgb d images with this program，but the output was ugly, is there any specific requirements for the format of input ?

**Comment by RuWang15** [comment]
Any progress? @Dzhange Did you find the way to make the 3D keypoints look better?

**Comment by Dzhange** [comment]
No... the output of this model is accurate but the draw function is not that good.  you can try to draw the limbs by your self

**Comment by RuWang15** [comment]
Thanks for the update! By the way did you collect your RGBD images with Kinect v2?

**Comment by Dzhange** [comment]
yes, but other collaborated RGBD image should work too.

**Comment by RuWang15** [comment]
Thank you very much!
