### ISSUE TITLE
Measure of accuracy 

### ISSUE THREAD

**Issue by Naykira** [lmb-freiburg/rgbd-pose3d#3]
Hi, thank you for releasing the code. I just had a question about the way the results are reported in your paper. Though you have compared the results with Tome et al., it is only visually expressed. Is there any additional resource online where you compare the results in terms of mean per joint position error (MPJPE) as well? 

Thanks!

**Comment by zimmerm** [comment]
Hi, in Table II of our paper we report "mean end point error per keypoint".
