### ISSUE TITLE
Hardware requirements?

### ISSUE THREAD

**Issue by brinij** [lmb-freiburg/rgbd-pose3d#4]
Hi,

I am trying to run your 3D human detection with RGB-D camera (Intel RealSense R200) and I would like to know what should be the hardware requirements? I have two GPUs detected by Tensorflow (Nvidia Quadro P4000 (8GB memory) and Nvidia GeForce GTX 1050 (4GB memory)) and I managed to run forward_pass.py on one and ROSNode.py on another but I am getting warnning : "Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.40GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.". So I could live with that if I get any meaningful result, but now TF tree of a human doesn't look correct. Now I am not sure is it because of the lack of memory or something else is wrong. 
(btw I can run OpenPose 2D detection on three cameras at the same time with this GPU configuration)

Thank you in advance and looking forward to your response!

**Comment by zimmerm** [comment]
Hi,
Sorry for the late reply.
I also get the warning, when I run it on my machine. I suspect that your issues arise from the fact that you use a R200 camera and not a Kinect v2 as we did. Can you check if problems persist with a Kinect v2?

**Comment by brinij** [comment]
Hi,

thanks for you reply. Finally I have managed to use it with other RGB-D cameras as well (Intel RealSense R200 and D435).  
Only what I changed was image encoding in RosNode.py : 
in `def color_callback(self, data):`
`cv_image = self.bridge.imgmsg_to_cv2(data, desired_encoding="rgb8")` 
and in `def depth_callback(self, data):`
`cv_image = self.bridge.imgmsg_to_cv2(data, desired_encoding="16UC1")`
