### ISSUE TITLE
Latency of ROS node

### ISSUE THREAD

**Issue by tlind** [lmb-freiburg/rgbd-pose3d#5]
Hi, thanks for sharing the results of your research! When trying out your ROS node, I noticed there is sometimes quite a bit of latency even though you set `queue_size` to 1 on both image subscribers. This is usually caused by a too small `buff_size`. Basically, the trick is that whenever you subscribe to large messages (such as images) and want to achieve low latency by setting a small `queue_size`, to supply the keyword argument `buff_size` to the constructor and set it to `queue_size * avg_msg_size_in_bytes`.

In your code example, I set buff_size to `10000000` (~10 MB), such that an average image message should now easily fit in there. This way, the messages won't be queued up anymore in the operating system's buffer that is inducing the latency (and you may not even need a separate processing thread anymore).

This issue is only relevant for rospy, not roscpp. See here for further details: https://github.com/ros/ros_comm/issues/536

**Comment by brinij** [comment]
Thanks, this helped a lot!

**Comment by twelsche** [comment]
Thanks for the suggestion. We included a buff_size in the image subscribers.
