### ISSUE TITLE
How to get the ground truth 3d keypoint locations through triangulation techniques?

### ISSUE THREAD

**Issue by Superlee506** [lmb-freiburg/rgbd-pose3d#6]
Thanks a lot for this work. I'm interested in the collection of MKV dataset, because my research interest is 3d human pose estimation. Could you please give some detailed information about the "triangulation techniques"?
Any suggestions will be appreciated.
![image](https://user-images.githubusercontent.com/13114675/45801335-386d7e80-bce6-11e8-904e-0c25b04347fd.png)

**Comment by RuWang15** [comment]
Any progress? @Superlee506

**Comment by zimmerm** [comment]
In its core we use Direct Linear Transform as described in Multiple View Geometry by Hartley&Zisserman. You can find an implementation of that in [OpenCV](https://docs.opencv.org/3.1.0/d0/dbd/group__triangulation.html)
