### ISSUE TITLE
How did you calibrate the Kinect v2 devices when collecting the MKV dataset?

### ISSUE THREAD

**Issue by allanwangliqian** [lmb-freiburg/rgbd-pose3d#7]
Hi, thank you so much for your work. We are interested in generating a pedestrian walking dataset using a similar approach. However due to the limited resources we have we want to first consult on how others have done it. Would you mind sharing with us a brief overview of your Kinect calibration method? Did you use any special technique to make it work?

**Comment by zimmerm** [comment]
For the dataset we used custom software based on OpenCV and Ceres for camera calibration.

**Comment by LETMEY** [comment]
@zimmerm Hi,Would you like to publish dataset?
