### ISSUE TITLE
Which is the channel order of Network output, [1, D, H, W, C] or [1, W, H, D, C] ?

### ISSUE THREAD

**Issue by Aki57** [lmb-freiburg/rgbd-pose3d#8]
Thanks for your work!
I follow your voxelposenet, rewrite it using Tensorlayer.
The 3D network‘s result from my own data is not so good, the channel order may be reason.
The annotations of function 'PoseNet3D._detect_scorevol' indicate "Tensor scorevolume is [1, D, H, W, C]".
I didn't found channel rearrangement in your following codes. But final result use the order of 'xyz'.

Any answers? Thanks a lot.

**Comment by zimmerm** [comment]
Discard the comment you found in the function mentioned. The tensor
represents [1, X, Y, Z, C] which is the usual CV camera coordinate frame
with X pointing right, Y down and Z positive in viewing direction.

**Comment by wqingzex** [comment]
@Aki57 dose your rewrite works? any open source codes?
