### ISSUE TITLE
How defines the intrinsic calibration data？

### ISSUE THREAD

**Issue by Aki57** [lmb-freiburg/rgbd-pose3d#9]
Very appreciated for your help and quick reply~
There is another question about wrapped depth image. As your article mentioned, the depth map is transformed into the color frame using the camera calibration.
The intrinsic calibration data in 'forward_pass.py' seems to be the product of depth cam's intrinsic parameters and scaling resolution ratios.
Why not use the color cam's intrinsic calibration directly when depth map was already in the color space?

**Comment by zimmerm** [comment]
The distinction of two separate coordinate frames stems from training time, where they really are different. Contrarily, in the ROS node setup image acquisition was done by a node that already warped everything into the same frame so I just chose the camera matrices accordingly. One could simplify the code for this case, youre right.
